site_name: cookiecutter-pythonic-project-bigdata-etl

theme:
  name: material
  language: zh
  features:
    - search.highlight
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

repo_url: https://github.com/pyloong/cookiecutter-pythonic-project-bigdata-etl
repo_name: pyloong/cookiecutter-pythonic-project-bigdata-etl
site_url: https://github.com/pyloong/cookiecutter-pythonic-project-bigdata-etl

plugins:
  - search

nav:
  - 文档: index.md
  - 使用说明: usage.md
  - 变更记录: changelog.md