[global]
message = 'This is in global settings'

# log-config
LOGPATH = '../../log/'
DEBUG = false
LOGLEVEL = 'INFO'
VERBOSE = false

# tmp task path
input_path = '../../data/input/car_price.csv'
output_path = '../../data/output'
